spring.datasource.url=jdbc:h2:mem:userdb
spring.datasource.username=anna
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
spring.h2.console.enabled=true
spring.data.redis.embedded=true
spring.cache.type=redis
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
server.port=8081