# DB
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:mem:userdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:anna}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=org.h2.Driver
server.port=8081

# Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# H2 Console
spring.h2.console.enabled=true

# Redis
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}